services:
  booksapi:
    build: .
    container_name: booksapi
    volumes:
      - ./:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - booksapi 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
