name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests with pytest
        id: test
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run tests with pytest

      - name: Handle test success
        if: success() # This step runs if pytest passes (exit code 0)
        run: |
          echo "All tests passed! 🎉"

      - name: Handle test failure
        if: failure() # This step runs if pytest fails (non-zero exit code)
        run: |
          echo "Tests failed. Please review the logs."
          exit 1
